### PR TITLE
Changed Aspect Ratio of Poster on Wall View

### PR DESCRIPTION
**Pull request by DerGary**
Changed the Aspect Ratio of the Poster on the Wall view from 1.58 to
1.5. to do this i had to change the small posters aspect ratios from
1.45 to 1.48 which is good because its closer to 1.5

Hey Jurialmunkey, the aspect ratio of the Posters on the Wall drove me mad so i changed it, maybe you want to change it too?

### CODE REVIEW

**Comment by jurialmunkey** [comment]
You've done the calculations wrong because you haven't accounted for the 10px of padding around the poster... The itemlayout height is 330, so 10px of padding makes the poster height 310px. 
310 / 1.5 = 206.66 
I round up to 207, hence a itemlayout height of 227 to accomodate the 10px padding.

Your ratio is actually 1.527 (310 / 203), whereas mine is 1.4975 which is much closer to 1.5

**Comment by DerGary** [comment]
I'm Sorry your right on that one, missed it. But the real reason why i changed all that is because the Big Poster, it isn't the same aspect ratio as on other views. 

If i calculated it right this time, the big poster 660x418 is 640x398 without padding, which is an aspect ratio of 1.608. Because i use this view as TvShow View and the Media Info as Episode view which also has the Big Poster, but on that view the poster is significantly wider, so I tried to change the Big Poster that it looks like the one on other views. But i had to take the Space from somewhere, and because i know you have strict padding rules, i couldn't take it from there and therefore i took it of the small Posters width. With my changes of the Big Poster to 660x440 (640x420 without padding) which is an aspect ratio of 1.524 the big poster looks a lot better and a lot more like the ones on other views, so i think the change from 1.5 to 1.527 on the small posters are an acceptable sacrifice.

The Only Other thing that would be possible is to change the Padding in some way

**Comment by jurialmunkey** [comment]
The poster width actually has to be 427 for 1.5 aspect (so 447 total). I think what I'm going to have to do is remove a poster column and increase the horizontal padding between posters a little bit

**Comment by jurialmunkey** [comment]
Actually, that doesn't work either -- the padding is far too much if I do that... hmmmm I don't know. I'm almost tempted to just remove the big poster and only show the extra info version.

**Comment by DerGary** [comment]
How about decreasing the content hight by 10 then you could have the big poster with 630x420 which is exactly 1.5 and the small posters with 305x203 which is 1.502

**Comment by jurialmunkey** [comment]
Okay I think I've fixed it now without reducing height. I increased the vertical padding between the rows slightly for the view with posters - this also allowed me to add an option to not have a big poster or the fanart (just the poster wall essentially).

**Pull request closed without merging**
