### PR TITLE
Added new viewtype: Icon Wall

### PR DESCRIPTION
**Pull request by perfectcolors**
I'm not sure if this viewtype fits with your vision of the skin, but I find it's nice for scrolling through large movie libraries.

icon-wall-view

As this is my first attempt at skin editing you may wish to review the changes, but I couldn't find anything wrong when I tested it.

(View_508_BigWall.xml is an edited version of View_55_Wall.xml)

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Good work. Problem is that it wont work if any furniture is enabled (clock, header, flags etc.) so can't really merge it with main skin.

**Comment by perfectcolors** [comment]
Includes_Furniture.xml was modified to hide clock, header, flags, weather and now playing info while this viewtype is active.

No worries if you don't wish to merge though.

**Comment by freeman212** [comment]
this looks nice and clean. good work, @perfectcolors.

**Comment by freeman212** [comment]
why wasn't this merged to master ? :( @ghost

**Pull request closed without merging**
