### PR TITLE
Update Includes_OSD.xml

### PR DESCRIPTION
**Pull request by Peelige**
Kodi 18 Leia fixes for PVR OSD (remaining time in clock / progress bar)

### CODE REVIEW

**Comment by Peelige** [comment]
Hi, my first time on GitHub - hope I've followed the correct process to apply the LiveTV OSD fixes for Leia !

**Comment by jurialmunkey** [comment]
Looks good. However, rather than using two label controls, it might be better to stick the label in a variable. Reducing the number of controls and visible conditions helps performance on low powered devices.

e.g.
``` xml
<label>$VAR[LabelOSDTime]</label>
```

And then in Includes_Labels.xml add the variable:
``` xml
<variable `name="LabelOSDTime">
    <value condition="VideoPlayer.Content(LiveTV)">$INFO[PVR.EpgEventElapsedTime]  /  $INFO[PVR.EpgEventDuration]</value>
    <value>$INFO[Player.Time]  /  $INFO[Player.Duration]</value>
<variable>
```


Do the same for the finish time also. If you can make those changes, I will merge the PR

**Comment by Peelige** [comment]
Hi thanks for the feedback and guidance on optimising the code.   The controls in question have been reduced from 4 to 2 and the label variables added to Includes_Labels.xml as another PR

**Comment by jurialmunkey** [comment]
Okay looks good! Merged.

For future reference, it is best to submit all the required changes as a single PR. If you commit and push the changes to the one branch, then github should just automatically update the changes in the PR.

Thanks for submitting! 😁

**Comment by Peelige** [comment]
Not a problem- always good to give something back.  After all it must have
taken you an age to code up in the first place!

Thanks for the info regarding a single PR.  I did look to see how I could
merge changes into 1, but now I know.  Thanks

**Pull request merged**
